{{- if .Values.PersistentVolume.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.PersistentVolume.name }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - {{ .Values.PersistentVolume.accessMode }}
  storageClassName: {{ .Values.PersistentVolume.storageClass }}
  resources:
    requests:
      storage: {{ .Values.PersistentVolume.size }}
{{- end }}