---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microservice.name" . }}
  namespace: {{ .Values.ns_name }}
  labels:
    app: {{ include "microservice.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "microservice.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "microservice.name" . }}
    spec:
      containers:
      - name: {{ include "microservice.name" . }}
        image: {{ .Values.image.name }}:{{ .Values.image.version }}
        command:
          - "redis-server"
        args:
          - "--protected-mode"
          - "no"
        ports:
        - containerPort: {{ .Values.service.src_port }}